
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Init
        run: |
         sudo apt-get update -y 
         sudo apt install git -y
         sudo npm install --global yarn

     
      - name: Install 
        run: |
          yarn
          yarn build
          
      - name: Upload 
        run: |
          npx ipfs-deploy ./build         

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: build
          FOLDER: build
          CLEAN: true 
